name: Download
on:
  workflow_dispatch:

jobs:
  descarga:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar herramientas
        run: |
          sudo apt-get install -y ffmpeg
          pip install yt-dlp requests curl-cffi

      - name: Abrir historial cifrado
        env:
          GPG_KEY: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          if [ -f archive.txt.gpg ]; then
            gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output archive.txt archive.txt.gpg
          else
            touch archive.txt
          fi

      - name: Ejecutar Script Ninja
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LISTA_USUARIOS: ${{ secrets.LISTA_USUARIOS }}
        run: python main.py

      - name: Cerrar caja fuerte y cifrar
        env:
          GPG_KEY: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --symmetric --passphrase="$GPG_KEY" --output archive.txt.gpg archive.txt
          rm archive.txt

      - name: Guardar historial y subir cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add archive.txt.gpg
          git commit -m "Historial actualizado (Cifrado)" || exit 0
          git pull --rebase origin main
          git push
